Feature/our clients react slick
citi-onboarding/Delta-odonto pull request #23
Opened 2020-12-12 02:11 UTC by vitoriapinheiro

## WHAT I DID
Created the carousel of the clients
## HOW TO TEST
1- On the terminal type:
`cd server`
`node index.js`
2- On another terminal but at the same time type:
`cd client`
`yarn start`
3- Then a page will open on your browser showing the carousel
You will see on the desktop version 2 pictures of two clients and the testimony and name of each client every time you scroll the slide

2020-12-12 02:41 UTC, lluk4z approved these changes, later dismissed

2020-12-12 03:33 UTC, js-dan requested changes
The arrows are not working.

2020-12-12 04:27 UTC, lluk4z approved these changes

2021-03-25 03:13 UTC, closed without merging

2021-03-25 03:13 UTC, sofiadinizms commented
Develop is ahead of this branch