Banner.js
citi-onboarding/Delta-odonto pull request #3
Opened 2020-11-26 01:27 UTC by vitoriapinheiro

## What I did
Created the model of the banner

2020-11-29 23:07 UTC, js-dan approved these changes

2020-11-29 23:29 UTC, lluk4z approved these changes

2020-11-30 22:08 UTC, lluk4z submitted a review, later dismissed

2020-11-30 22:37 UTC, js-dan requested changes
The banner route is incomplete.

2020-11-30 22:37 UTC, js-dan commented on server/routes/index.js
> +    Banner.model.find((err, data) => {
This route is incomplete.

2020-12-03 21:47 UTC, js-dan approved these changes

2020-12-03 21:50 UTC, lluk4z approved these changes

2020-12-03 21:50 UTC, merged