Feature/navbar
citi-onboarding/Delta-odonto pull request #8
Opened 2020-12-02 20:46 UTC by lluk4z

## What i did

- Creation of the navbar

## How to teste

- On one terminal you should type the  following commands to access the client folder and run the Keystone example
`cd client`
`npm start` or `yarn start` 

- Now you should see the navbar with the logo in the left corner and the sections in the navbar "Quem somos - Nossos serviços - Nossos clientes - Blog  - Contato"

- when you set the responsive mode, you should see the menu hamburger int ther rght corner  and the logo in the left corner

- when you click in the menu hamburger you should see the side drawer with the sections Quem somos - Nossos serviços - Nossos clientes - Blog  - Contato column aligned

2020-12-08 17:17 UTC, vitoriapinheiro submitted a review, later dismissed

2020-12-08 20:49 UTC, js-dan requested changes
This branch has conflicts that must be resolved.

2020-12-09 03:04 UTC, js-dan approved these changes

2020-12-09 05:16 UTC, vitoriapinheiro approved these changes

2020-12-09 14:28 UTC, vitoriapinheiro approved these changes

2020-12-09 17:49 UTC, js-dan approved these changes

2020-12-09 17:53 UTC, merged